eureka:
  client:
     healthcheck:
       enabled: true
     registryFetchIntervalSeconds: 5
     region: default
     serviceUrl:
        defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

spring:
  application:
    name: authService
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://dev-vm-00:3306/dev1?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: test
    #initialization-mode: always
    #continue-on-error: true
    hikari:
      maximum-pool-size: 3

server:
  port: 8097

logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        SQL: debug
        type: trace
        
security:
  permit: false
  authUser: root
  authPwd: pwd
