mongodb:
  database: dataCatalogSZRCB
  uri: localhost:27017
  username: root
  password: dataPlatform
  maxConnectionIdleTime: 600000
essearch:
  host: localhost
  port: 9300
  cluster: dataSharing

eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

spring:
  application:
    name: dataCatalog
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/szrcb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 3
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtualHost: szrcb
    exchange: metadata-exchange
    dataCatalogQueue: dataCatalog-mdqueue
    sqlEngineExchange: sqlEngine-exchange
    sqlEngineQueue: sqlEngine-queue
    labelQueue: label-queue
    sampleQueue: sample-queue
    dataQualityQueue: dataQuality-queue

server:
  port: 8079

feign:
  client:
    config:
      default:
        ReadTimeout: 30000
        ConnectTimeout: 30000
tableModel:
  openCache: true
  auditKey: audit
  sampleQueueSize: 5
logging:
  level:
    org:
      springframework:
        security: debug

