mongodb:
  database: dataCatalogDemo
  uri: dev-vm-00:27017
  username: root
  password: dataPlatform

essearch:
  host: dev-vm-00
  port: 9300
  cluster: dataSharing

eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost

spring:
  application:
    name: dataCatalog
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
  datasource:
    url: jdbc:mysql://dev-vm-00:3306/dev1?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: test
    hikari:
      maximum-pool-size: 3
  rabbitmq:
    host: dev-vm-00
    port: 5672
    username: guest
    password: guest
    virtualHost: demo
    exchange: metadata-exchange
    dataCatalogQueue: dataCatalog-mdqueue
    sqlEngineExchange: sqlEngine-exchange
    sqlEngineQueue: sqlEngine-queue
    labelQueue: label-queue
    sampleQueue: sample-queue
    dataQualityQueue: dataQuality-queue

server:
  port: 8079

feign:
  client:
    config:
      default:
        ReadTimeout: 30000
        ConnectTimeout: 30000
tableModel:
  openCache: true
  auditKey: audit
  sampleQueueSize: 5
