server:
  port: 8095
spring:
  application:
    name: integrationMstr
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://dev-vm-00:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    initialization-mode: always
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
  session:
    store-type: redis
    redis: 
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
    serviceUrl:
      defaultZone:  http://localhost:8081/eureka/
  instance:
    preferIpAddress : false
    hostname: localhost
logging:
  level:
    org:
      springframework:
        security: debug
security:
  permit: false
  authUser: root
  authPwd: pwd

mstr:
  url:
    prefix: http://192.168.0.40:8080/MicroStrategy/servlet/mstrWeb?evt=3187&src=mstrWeb.3187&parentFolderId=EFCEF27446188E0176438CACD04A79FE&Server=DESKTOP-L6PPDEH&Project=MicroStrategy%20Tutorial
