server:
  port: 8095
spring:
  application:
    name: integrationMstr
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://dev-vm-00:3306/szrcb?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: test
    password: test
    initialization-mode: always
    continue-on-error: true
    hikari:
      maximum-pool-size: 5
  session:
    store-type: redis
    redis: 
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
    serviceUrl:
      defaultZone: http://dev-vm-21:8081/eureka/
  instance:
    preferIpAddress : false
    hostname: dev-vm-21
logging:
  level:
    org:
      springframework:
        security: debug
security:
  permit: false
  authUser: root
  authPwd: pwd

mstr:
  url:
    prefix: http://139.198.126.155:6080/MicroStrategy/servlet/
    prefix1: http://139.198.126.155:6080/MicroStrategy/servlet/
    report: mstrWeb?evt=3187&src=mstrWeb.3187&parentFolderId=8D67909211D3E4981000E787EC6DE8A4&Server=1A5EG1P5ANCBGIX&Project=MicroStrategy%20Tutorial
    init: taskProc?taskId=createUserAndDSTask&taskEnv=xhr&taskContentType=json
