server:
  port: 8099

security:
  permit: false
mongodb:
  database: metadataRepoSZRCB
  uri: localhost:27017
  username: root
  password: root
  options: ?AutoConnectRetry=true&sslEnabled=true&socketKeepAlive=true
  lower_case_metadata_names: false

essearch:
      host: localhost
      port: 9300
      cluster: dataSharing
      logIndexName: metadata_log #logstash 注意不能识别大写
      metadataIndexName: keymobile_metadata
eureka:
  client:
     registryFetchIntervalSeconds: 5
     region: default
     serviceUrl:
        defaultZone:  http://localhost:8081/eureka/
  instance:
     preferIpAddress : false
     hostname: localhost

spring:
  application:
    name: metadataRepo
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: localhost
    port: 6379
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtualHost: szrcb
      exchange: metadata-exchange
      dataCatalogQueue: dataCatalog-mdqueue
  datasource:
    url: jdbc:mysql://localhost:3306/szrcb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 3
  mail:
    host: smtp.163.com
    port: 25
    protocol: smtp
    username: cr_gu@163.com
    password: ghy0914
    default-encoding: UTF-8
    to: laigx@keymobile.com.cn
    sendFlag: false
    properties:
      mail:
        auth: true
        starttls:
          enable: true
          required: true
logging:
  level:
    org:
      springframework:
        security: debug
