server:
  port: 8762

spring:
  application:
    name: proxy
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/szrcb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maximum-pool-size: 5
  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

eureka:
  client:
    registerWithEureka: false
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone:  http://localhost:8081/eureka/

zuul:
  prefix: /api
  sensitive-headers:

logging:
  level:
    org.springframework.security: INFO

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

redirect-url:
  system-management: http://localhost:8089/views/login.html
