eureka:
  client:
    registryFetchIntervalSeconds: 5
    region: default
    serviceUrl:
      defaultZone:  http://localhost:8081/eureka/
    enabled: true
  instance:
    prefer-ip-address: false
    hostname: dev-vm-21 

spring:
  application:
    name: sqlEngine
  jta:
    enabled: false
  session:
    store-type: redis
    redis:
      namespace: dataplatformtest
  redis:
    host: dev-vm-00
    port: 6379
  datasource:
    url: jdbc:mysql://dev-vm-00:3306/szrcb?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: test
    password: test
    hikari:
      maximum-pool-size: 3
  rabbitmq:
    host: dev-vm-00
    port: 5672
    username: guest
    password: guest
    virtualHost: szrcb
    sqlEngineExchange: sqlEngine-exchange
    sqlEngineQueue: sqlEngine-queue

server:
  port: 8072

sqlEngine:
  host: 0.0.0.0
  jdbcPort: 50201
  odbcPort: 50202
  dbPoolMaxSize: 10
  dbPoolMinSize: 2
  maxSocketThreads: 50
  maxAsyncThreads: 50
  maxActivePlans: 10

security:
  authUser: root
  authPwd: pwd 
  permit: false 

feign:
  client:
    config:
      default:
        connectTimeout: 40000
        ReadTimeout: 40000

self:
  config:
    output: 192.168.0.212,50201
